import React, { Suspense } from "react";
import type { Metadata } from "next";
import { urbanist } from "@/font";
import "./globals.css";
import Loader from "@/components/common/Loader";
import RouteLoader from "@/components/common/RouteLoader";
import { Navbar } from "@/components/common/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const icons = {
  icon: [
    { url: "/harmy.svg" },
    { url: "/harmy.png", sizes: "32x32", type: "image/png" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${urbanist.variable} antialiased`}>
        <RouteLoader />
        <Navbar />
        <Suspense fallback={<Loader />}>{children}</Suspense>
      </body>
    </html>
  );
}
