import React, { Suspense } from "react";
import type { Metadata } from "next";
import { urbanist } from "@/font";
import "./globals.css";
import Loader from "@/components/common/Loader";
import RouteLoader from "@/components/common/RouteLoader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${urbanist.variable} antialiased`}>
        <RouteLoader />
        <Suspense fallback={<Loader />}>{children}</Suspense>
      </body>
    </html>
  );
}
